#pragma once
#include <cstdint>
#include <utility>

constexpr uint32_t COND_BITS = 0xF0000000; // Bits 31-28
constexpr uint32_t OPCODE_BITS = 0x1E00000; // Bits 24-21

constexpr int DATA_PROCESSING_SET_CPSR_FLAGS_SHIFT = 20;

constexpr uint32_t OPERAND2_MASK = 0xFFF;

constexpr uint32_t OPCODE_MASK = 0xF;
constexpr int OPCODE_SHIFT = 21;

constexpr uint32_t INSTRUCTION_TYPE_MASK = 0b11;
constexpr int INSTRUCTION_TYPE_SHIFT = 26;

constexpr int OPERAND2_MODE_SHIFT = 25;

constexpr uint32_t CONDITION_MASK = 0xF;
constexpr int CONDITION_SHIFT = 28;

class GBA_CPU;

struct Operand2Result 
{
    uint32_t value;
    uint32_t carryOut : 1; // Store only 1 bit of information
};

enum ShiftType
{
    LSL,
    LSR,
    ASR,
    ROR
};

struct DataProcessing_Decoded
{
    uint8_t rnIndex, rdIndex;
    Operand2Result op2;
    bool setCpsrFlag; // Whether or not to set CPSR Flags
};

struct Multiply_Decoded
{
    uint8_t rdIndex, rnIndex, rsIndex, rmIndex;
    bool accumulateFlag, setCpsrFlag;
};

struct MultiplyLong_Decoded
{
    uint8_t rdHiIndex, rdLoIndex, rsIndex, rmIndex;
    bool signedFlag, accumulateFlag, setCpsrFlag;
};

struct SingleDataSwap_Decoded
{
    uint8_t rnIndex, rdIndex, rmIndex;
    bool bFlag;
};

struct HalfwordDataTransfer_Decoded
{
    uint8_t rnIndex, rdIndex;
    bool pFlag, uFlag, iFlag, wFlag, lFlag;
    bool sFlag, hFlag;
};

struct SingleDataTransfer_Decoded
{
    uint8_t rnIndex, rdIndex;
    bool pFlag, uFlag, iFlag, wFlag;
    bool lFlag, bFlag;
    uint16_t offsetBits;
};



DataProcessing_Decoded DataProcessing_Decode(uint32_t instruction, GBA_CPU& cpu);
Multiply_Decoded Multiply_Decode(uint32_t instruction);
MultiplyLong_Decoded MultiplyLong_Decode(uint32_t instruction);
SingleDataSwap_Decoded SingleDataSwap_Decode(uint32_t instruction);
/* Flag Definitions for HalfwordDataTransfer:

BIT 24 - Pre/Post indexing (P)
P == 0 - Indicates post-indexed addressing, base register value is used for memory address, the offset is
then applied to the base register value and written back to the base register
P == 1 - Indicates offset addressing OR pre-indexed addressing (W bit determines which of these two)
The memory address is generated by applying the offset to the base register value;

BIT 23 - Up/Down (U)
U - Indicates whether to add (U == 1) or subtract (U == 0) to the base register value.

BIT 22 - Immediate (I)
I - Immediate (I == 1) vs Register offset (I == 0)

BIT 21 - Writeback (W)
W - if P == 0, W bit must be 0 or the instruction is UNPREDICTABLE
    if P == 1 && W == 1 - Pre-indexed Addressing - Memory address is written back to the base register
    if P == 1 && W == 0 - Offset addressing - Base register is unchanged

BIT 20 - Load/Store (L)
L - Load (L == 1) vs Store (L == 0)

BIT 6
S - Signed (S == 1) vs unsigned (S == 0) halfword access

BIT 5
H - Halfword (H == 1) vs byte (H == 0) access
*/
HalfwordDataTransfer_Decoded HalfwordDataTransfer_Decode(uint32_t instruction);
// NOTE: I FLAG == 0 MEANS IMMEDIATE OFFSET
SingleDataTransfer_Decoded SingleDataTransfer_Decode(uint32_t instruction);




enum class InstructionCategory 
{
    DataProcessing,
    Multiply,
    LoadStore,
    Branch,
    Swap,
    SoftwareInterrupt,
    Coprocessor,
    Undefined
};

enum class DataProcessingOpcode
{
    AND, EOR, SUB, RSB,
    ADD, ADC, SBC, RSC,
    TST, TEQ, CMP, CMN,
    ORR, MOV, BIC, MVN
};

enum InstructionPattern : uint8_t 
{
    PATTERN_00, // Data Processing (immediate/register) and Misc: Multiply, Swap, Halfword transfer, Branch (BX)
    PATTERN_01, // Single Data Transfer or Undefined (bit 4 decides)
    PATTERN_10, // Block Data Transfer (LDM/STM) or Branch
    PATTERN_11, // Coprocessor or Software Interrupt
};

/// @brief Extracts the second operand for data processing
/// @param instruction The current instruction being executed
/// @param isImmediateValue Immediate value flag (bit 25)
/// @return Operand2 (bits 11-0)
Operand2Result ExtractOperand2(uint32_t instruction, GBA_CPU& cpu);

DataProcessingOpcode GetDataProcessingOpcode(uint32_t instruction);

Operand2Result ShiftByRegister(uint16_t operand2, ShiftType shiftType, GBA_CPU& cpu);
Operand2Result ShiftByImmediate(uint16_t operand2, ShiftType shiftType,  GBA_CPU& cpu);

inline bool CheckBits(uint32_t instruction, uint32_t shift, uint32_t mask, uint32_t expected)
{
    return ((instruction >> shift) & mask) == expected;
}

uint32_t ZeroExtendTo32(uint8_t value);
uint32_t ZeroExtendTo32(uint16_t value);

int32_t SignExtendTo32(uint8_t value);
int32_t SignExtendTo32(uint16_t value);
