#pragma once
#include <cstdint>
#include <utility>
#include "Core/CPU/Instructions/Conditions.hpp"

class GBA_CPU;

enum class DataProcessingOpcode
{
    AND, EOR, SUB, RSB,
    ADD, ADC, SBC, RSC,
    TST, TEQ, CMP, CMN,
    ORR, MOV, BIC, MVN
};

using InstructionFunction = void (*)(uint32_t, GBA_CPU&); // Instruction Function Pointer alias

struct Instruction
{
    uint32_t rawInstruction;
    InstructionFunction function = nullptr;
    bool valid = false;
};

struct ShifterOperand 
{
    bool shifted = false;
    uint32_t value;
    uint32_t carryOut : 1; // Store only 1 bit of information
};

struct DataProcessing_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    uint16_t shifterOperandBits;
    DataProcessingOpcode opcode;
    bool setCPSRFlag, immediateFlag;
};

struct Multiply_Decoded
{
    Condition condition;
    uint8_t rdIndex, rnIndex, rsIndex, rmIndex;
    bool accumulateFlag, setCPSRFlag;
};

struct MultiplyLong_Decoded
{
    Condition condition;
    uint8_t rdHiIndex, rdLoIndex, rsIndex, rmIndex;
    bool signedFlag, accumulateFlag, setCPSRFlag;
};

struct SingleDataSwap_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex, rmIndex;
    bool bFlag;
};

struct HalfwordDataTransfer_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    uint16_t offsetBits;
    bool pFlag, uFlag, iFlag, wFlag, lFlag;
    bool sFlag, hFlag;
};

struct SingleDataTransfer_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    bool iFlag; // 0 means immediate offset weirdly enough
    bool pFlag, uFlag, wFlag;
    bool lFlag, bFlag;
    uint16_t offsetBits;
};

struct BlockDataTransfer_Decoded
{
    Condition condition;
    uint8_t rnIndex;

    /* Has two meanings: 

    P == 0 indicates that the word addressed by Rn is INCLUDED in the range of memory 
    locations accessed, at the top (U == 0) or at the bottom (U == 1) of that range.

    P == 1 indicates that the word addressed by Rn is EXCLUDED from the range of memory
    locations accessed and lies one word beyond the top of the range (U == 0) or one 
    word below the bottom of the range (U == 1)
    
    */  
    bool pFlag; 
    /* Indicates that transfer is made upwards (U == 1) 
    or downwards (U == 0) from the base register
    */
    bool uFlag; 

    /*  Special Cases:
        For Load Multiples (LDMs) that load the PC, the S bit indicates that the CPSR
        is loaded from the current mode SPSR - Therefore LDM with S bit set is 
        UNPREDICTABLE in user/system mode (no SPSR to load)

        For LDMs that do not load the PC, the S bit indicates that when the processor is 
        in a privileged mode (any mode other than USER), the USER mode banked registers 
        are transferred instead of the registers of the current mode
    */
    bool sFlag;

    /* Writeback, increment (U == 1) or decrement (U == 0) by 
    (4 * number of registers) in the register list */
    bool wFlag;

    // Load (L == 1) or Store (L == 0)
    bool lFlag;
    // Bit 0 is R0, bit 15 is R15
    uint16_t registerList;
};

DataProcessing_Decoded DataProcessing_Decode(uint32_t instruction);
Multiply_Decoded Multiply_Decode(uint32_t instruction);
MultiplyLong_Decoded MultiplyLong_Decode(uint32_t instruction);
SingleDataSwap_Decoded SingleDataSwap_Decode(uint32_t instruction);
/* Flag Definitions for HalfwordDataTransfer:

BIT 24 - Pre/Post indexing (P)
P == 0 - Indicates post-indexed addressing, base register value is used for memory address, the offset is
then applied to the base register value and written back to the base register
P == 1 - Indicates offset addressing OR pre-indexed addressing (W bit determines which of these two)
The memory address is generated by applying the offset to the base register value;

BIT 23 - Up/Down (U)
U - Indicates whether to add (U == 1) or subtract (U == 0) to the base register value.

BIT 22 - Immediate (I)
I - Immediate (I == 1) vs Register offset (I == 0)

BIT 21 - Writeback (W)
W - if P == 0, W bit must be 0 or the instruction is UNPREDICTABLE
    if P == 1 && W == 1 - Pre-indexed Addressing - Memory address is written back to the base register
    if P == 1 && W == 0 - Offset addressing - Base register is unchanged

BIT 20 - Load/Store (L)
L - Load (L == 1) vs Store (L == 0)

BIT 6
S - Signed (S == 1) vs unsigned (S == 0) halfword access

BIT 5
H - Halfword (H == 1) vs byte (H == 0) access
*/
HalfwordDataTransfer_Decoded HalfwordDataTransfer_Decode(uint32_t instruction);
// NOTE: I FLAG == 0 MEANS IMMEDIATE OFFSET
SingleDataTransfer_Decoded SingleDataTransfer_Decode(uint32_t instruction);

BlockDataTransfer_Decoded BlockDataTransfer_Decode(uint32_t instruction);

enum class InstructionCategory 
{
    DataProcessing,
    Multiply,
    LoadStore,
    Branch,
    Swap,
    SoftwareInterrupt,
    Coprocessor,
    Undefined
};

enum InstructionPattern : uint8_t 
{
    PATTERN_00, // Data Processing (immediate/register) and Misc: Multiply, Swap, Halfword transfer, Branch (BX)
    PATTERN_01, // Single Data Transfer or Undefined (bit 4 decides)
    PATTERN_10, // Block Data Transfer (LDM/STM) or Branch
    PATTERN_11, // Coprocessor or Software Interrupt
};


DataProcessingOpcode GetDataProcessingOpcode(uint32_t instruction);

inline bool CheckBits(uint32_t instruction, uint32_t shift, uint32_t mask, uint32_t expected)
{
    return ((instruction >> shift) & mask) == expected;
}

uint32_t ZeroExtendTo32(uint8_t value);
uint32_t ZeroExtendTo32(uint16_t value);

int32_t SignExtendTo32(uint8_t value);
int32_t SignExtendTo32(uint16_t value);

inline uint32_t CarryFrom(uint64_t result)
{
    return static_cast<uint32_t>(result >> 32);
}

uint32_t NumberOfSetBitsIn(uint32_t value);
