#pragma once
#include <cstdint>
#include <utility>
#include "Core/CPU/Instructions/CPU_Conditions.hpp"

constexpr uint32_t INSTRUCTION_TYPE_MASK = 0b11;
constexpr int INSTRUCTION_TYPE_SHIFT = 26;

constexpr int OPERAND2_MODE_SHIFT = 25;

constexpr uint32_t CONDITION_MASK = 0xF;
constexpr int CONDITION_SHIFT = 28;

class GBA_CPU;

enum class DataProcessingOpcode
{
    AND, EOR, SUB, RSB,
    ADD, ADC, SBC, RSC,
    TST, TEQ, CMP, CMN,
    ORR, MOV, BIC, MVN
};

using InstructionFunction = void (*)(uint32_t, GBA_CPU&); // Instruction Function Pointer alias

struct ShifterOperand 
{
    uint32_t value;
    uint32_t carryOut : 1; // Store only 1 bit of information
};

struct DataProcessing_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    uint16_t shifterOperandBits;
    DataProcessingOpcode opcode;
    bool setCPSRFlag, immediateFlag;
};

struct Multiply_Decoded
{
    Condition condition;
    uint8_t rdIndex, rnIndex, rsIndex, rmIndex;
    bool accumulateFlag, setCPSRFlag;
};

struct MultiplyLong_Decoded
{
    Condition condition;
    uint8_t rdHiIndex, rdLoIndex, rsIndex, rmIndex;
    bool signedFlag, accumulateFlag, setCPSRFlag;
};

struct SingleDataSwap_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex, rmIndex;
    bool bFlag;
};

struct HalfwordDataTransfer_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    uint16_t offsetBits;
    bool pFlag, uFlag, iFlag, wFlag, lFlag;
    bool sFlag, hFlag;
};

struct SingleDataTransfer_Decoded
{
    Condition condition;
    uint8_t rnIndex, rdIndex;
    bool iFlag; // 0 means immediate offset weirdly enough
    bool pFlag, uFlag, wFlag;
    bool lFlag, bFlag;
    uint16_t offsetBits;
};



DataProcessing_Decoded DataProcessing_Decode(uint32_t instruction);
Multiply_Decoded Multiply_Decode(uint32_t instruction);
MultiplyLong_Decoded MultiplyLong_Decode(uint32_t instruction);
SingleDataSwap_Decoded SingleDataSwap_Decode(uint32_t instruction);
/* Flag Definitions for HalfwordDataTransfer:

BIT 24 - Pre/Post indexing (P)
P == 0 - Indicates post-indexed addressing, base register value is used for memory address, the offset is
then applied to the base register value and written back to the base register
P == 1 - Indicates offset addressing OR pre-indexed addressing (W bit determines which of these two)
The memory address is generated by applying the offset to the base register value;

BIT 23 - Up/Down (U)
U - Indicates whether to add (U == 1) or subtract (U == 0) to the base register value.

BIT 22 - Immediate (I)
I - Immediate (I == 1) vs Register offset (I == 0)

BIT 21 - Writeback (W)
W - if P == 0, W bit must be 0 or the instruction is UNPREDICTABLE
    if P == 1 && W == 1 - Pre-indexed Addressing - Memory address is written back to the base register
    if P == 1 && W == 0 - Offset addressing - Base register is unchanged

BIT 20 - Load/Store (L)
L - Load (L == 1) vs Store (L == 0)

BIT 6
S - Signed (S == 1) vs unsigned (S == 0) halfword access

BIT 5
H - Halfword (H == 1) vs byte (H == 0) access
*/
HalfwordDataTransfer_Decoded HalfwordDataTransfer_Decode(uint32_t instruction);
// NOTE: I FLAG == 0 MEANS IMMEDIATE OFFSET
SingleDataTransfer_Decoded SingleDataTransfer_Decode(uint32_t instruction);


enum class InstructionCategory 
{
    DataProcessing,
    Multiply,
    LoadStore,
    Branch,
    Swap,
    SoftwareInterrupt,
    Coprocessor,
    Undefined
};



enum InstructionPattern : uint8_t 
{
    PATTERN_00, // Data Processing (immediate/register) and Misc: Multiply, Swap, Halfword transfer, Branch (BX)
    PATTERN_01, // Single Data Transfer or Undefined (bit 4 decides)
    PATTERN_10, // Block Data Transfer (LDM/STM) or Branch
    PATTERN_11, // Coprocessor or Software Interrupt
};


DataProcessingOpcode GetDataProcessingOpcode(uint32_t instruction);

inline bool CheckBits(uint32_t instruction, uint32_t shift, uint32_t mask, uint32_t expected)
{
    return ((instruction >> shift) & mask) == expected;
}

uint32_t ZeroExtendTo32(uint8_t value);
uint32_t ZeroExtendTo32(uint16_t value);

int32_t SignExtendTo32(uint8_t value);
int32_t SignExtendTo32(uint16_t value);

inline uint32_t CarryFrom(uint64_t result)
{
    return static_cast<uint32_t>(result >> 32);
}
